### ISSUE TITLE
recorder

### ISSUE THREAD

**Issue by Le-Khuong** [banbuskox/dfhtyxvzexrxgfdzgzfdvfdz#1]
since this thing still work, can. i get the recorder script?

**Comment by banbuskox** [comment]
> since this thing still work, can. i get the recorder script?

Recorder is open-source on my site but my domain had expired so ill send you direct link.
https://banbusscripts.netlify.app/Scripts/TDSRecorder (It's probably not even working)

**Comment by Le-Khuong** [comment]
Ty
